def test_exception():
    raise Exception('oops')

def test_error():
    assert 0 != 0
